---
- include: app-facts.yml

- when: setup_postgres == True
  include: postgres-facts.yml


- include: project.yml


- when: build_frontend == True
  include: frontend.yml


- when: (action == "deploy" and deploy_type == "restart")
  include: action-deploy-type-restart.yml


- when: (action == "deploy" and deploy_type == "upgrade")
  include: action-deploy-type-upgrade.yml


- name: start nginx using monit
  monit: name="nginx" state=started
