---
- name: stop app
  monit: name="{{ app_name }}" state=stopped


- name: delete if release exists
  command: bash -lc "mix release.clean" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: "compile and release"
  command: bash -lc 'SERVER=1 mix do compile, release' chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
    PORT: "{{ app_port }}"


- name: "create .current-release dir"
  file:
    path: "{{project_path}}/.current-release"
    state: directory
    recurse: yes
  remote_user: "{{ deployer }}"


- name: "copy release"
  command: "cp {{ project_path }}/rel/{{ app_name }}/releases/{{ app_version }}/{{ app_name }}.tar.gz {{ project_path }}/.current-release/"
  remote_user: "{{ deployer }}"


- name: "untar release"
  command: "tar -xf /tmp/test.tar.gz" chdir="{{project_path}}/.current-release"


- name: start app
  monit: name="{{ app_name }}" state=started
