---
- include: common.yml

- name: "check for swap file path"
  stat: path="/swap"
  register: swap_info


- when: create_swap_file == True and swap_info.stat.exists == False
  include: create-swap-file.yml


- include: pip.yml
- include: deployer-user.yml
- include: asdf.yml


- when: setup_postgres == True
  include: postgres-facts.yml


- include: app-facts.yml

- when: setup_postgres == True
  include: postgres.yml


- include: project.yml


- when: build_frontend == True
  include: frontend.yml

- include: nginx.yml
- include: monit.yml

- name: start nginx using monit
  monit: name="nginx" state=started

- when: (action == "deploy" and deploy_type == "restart")
  include: action-deploy-type-restart.yml

- when: (action == "deploy" and deploy_type == "upgrade")
  include: action-deploy-type-upgrade.yml


- name: reload nginx config
  command: "nginx -s reload"
