---
- name: delete release
  command: bash -lc "mix release.clean" chdir="{{ project_path }}"
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_as }}"


- name: "compile and release"
  command: bash -lc 'mix do compile, release' chdir="{{ project_path }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
    PORT: "{{ app_port }}"
    SERVER: 1
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_as }}"


- name: stop app
  monit: name="{{ app_name }}" state=stopped
  become: "{{primary_user_sudo}}"


- name: start app
  monit: name="{{ app_name }}" state=started
  become: "{{primary_user_sudo}}"

###################

- name: "delete .current-release dir"
  file:
    path: "{{project_path}}/.current-release"
    state: absent
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_as }}"


- name: "create fresh .current-release dir"
  file:
    path: "{{project_path}}/.current-release"
    state: directory
    recurse: yes
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_as }}"


- name: "set compiled release tar path"
  set_fact: compiled_release_tar_path="{{ project_path }}/rel/{{ app_name }}/releases/{{ app_version }}/{{ app_name }}.tar.gz"


- name: "set current release tar path"
  set_fact: current_release_tar_path="{{ project_path }}/.current-release/{{app_name}}-{{app_version}}.tar.gz"


- name: "copy release"
  command: "cp {{compiled_release_tar_path}} {{current_release_tar_path}}"
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_as }}"


- name: "untar release"
  unarchive:
    src: "{{current_release_tar_path}}"
    dest: "{{project_path}}/.current-release"
    mode: 0777
    copy: no
    owner: "{{ deploy_as }}"
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_as }}"


- name: start app
  monit: name="{{ app_name }}" state=started
