---
- name: "create or get secret_key_base"
  set_fact:
    secret_key_base: "{{ lookup('password', app_credentials_dir + '/secret-key-base' + ' chars=ascii_letters,digits,punctuation length=' + secret_key_base_length) }}"
  become: "{{primary_user_sudo}}"


- name: detect endpoint module
  command: grep -m 1 -o '[[:alnum:]]*.Endpoint' {{ project_path }}/config/dev.exs
  register: grep_endpoint_module
  ignore_errors: true


- name: set app_endpoint_module fact
  set_fact: app_endpoint_module="{{ grep_endpoint_module.stdout }}"


- name: detect repo module
  command: grep -m 1 -o '[[:alnum:]]*.Repo' {{ project_path }}/config/dev.exs
  register: grep_repo_module
  ignore_errors: true


- name: set app_repo_module fact
  set_fact: app_repo_module="{{ grep_repo_module.stdout }}"
