---
- name: "install system packages"
  apt: name="{{ item }}" update_cache=yes
  with_items:
    - curl
    - wget
    - unzip
    - git
    - python-apt
    - automake
    - autoconf
    - libreadline-dev
    - libncurses-dev
    - libssl-dev
    - libyaml-dev
    - libxslt-dev
    - libffi-dev
    - libtool
    - unixodbc-dev
