---
- name: create file
  file: path=/swap state=touch mode=0600
  become: "{{primary_user_sudo}}"


- name: write blocks
  command: "dd if=/dev/zero of=/swap bs=1024 count={{ swap_size }}"
  become: "{{primary_user_sudo}}"


- name: setup swap area in /swap
  command: "mkswap /swap"
  become: "{{primary_user_sudo}}"


- name: swapon
  command: "swapon /swap"
  become: "{{primary_user_sudo}}"


- name: append swap info to fstab
  lineinfile: dest=/etc/fstab line="/swap    none    swap    sw    0    0"
  become: "{{primary_user_sudo}}"


- name: set swappiness in /proc/sys/vm/swappiness
  command: bash -lc "echo 10 | sudo tee /proc/sys/vm/swappiness"
  become: "{{primary_user_sudo}}"


- name: set swappiness in /etc/sysctl.conf
  command: bash -lc "echo vm.swappiness = 10 | sudo tee -a /etc/sysctl.conf"
  become: "{{primary_user_sudo}}"
