---
- name: "clone project"
  git:
    repo: "{{ project_repo }}"
    version: "{{ git_ref }}"
    dest: "{{ project_path }}"
    accept_hostkey: True
  remote_user: "{{ deployer }}"


- name: "install tool versions"
  command: bash -lc 'asdf install' chdir="{{ project_path }}"
  async: 1800
  remote_user: "{{ deployer }}"


- name: "generate secret key base"
  command: "openssl rand -base64 {{ secret_key_base_length }}"
  register: openssl_random_string


- name: set secret_key_base
  set_fact: secret_key_base="{{ openssl_random_string.stdout }}"


- name: add prod.secret.exs from template
  template:
    src: templates/prod.secret.exs.j2
    dest: "{{ project_path}}/config/prod.secret.exs"


- name: install hex
  command: bash -lc "mix local.hex --force" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: install rebar
  command: bash -lc "mix local.rebar --force" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: "fetch mix dependencies"
  command: bash -lc 'mix deps.get' chdir="{{ project_path }}"
  async: 900
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
