---
- name: "create release using exrm"
  command: bash -lc 'SERVER=1 mix release' chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
    PORT: "{{ app_port }}"


- name: "ensure running app is stopped"
  monit: name="{{ project_name }}" state=stopped


- name: "start the app again"
  monit: name="{{ project_name }}" state=started
