tasks:

  - include: setup.yml
    when: action == "setup"


  - include: elixir-project.yml

  - when: "build_frontend == True"
    include: frontend.yml

  - include: elixir-release.yml

  - name: start app daemon using monit
    monit: name="{{ project_name }}" state=started
