---

- name: "Set primary_user_sudo to True if non-root user"
  set_fact: primary_user_sudo=True
  when: primary_user != "root"


- when: action == "remove-app"
  include: action-remove-app.yml

- when: action == "setup"
  include: action-setup.yml

- when: action == "deploy"
  include: action-deploy.yml

- when: action == "migrate"
  include: action-migrate.yml

- when: action == "run-cmd"
  include: action-run-cmd.yml
