---
- when: action == "setup"
  include: common.yml

- when: action == "setup"
  name: "check for swap file path"
  stat: path="/swap"
  register: swap_info

- when: "action == 'setup' and create_swap_file == True and swap_info.stat.exists == False"
  include: create-swap-file.yml

- when: action == "setup"
  include: pip.yml

- when: action == "setup"
  include: deployer-user.yml

- when: action == "setup"
  include: asdf.yml

- when: "setup_postgres == True and database_name is not defined"
  name: "calculate database name"
  set_fact: "database_name={{ project_name }}_prod"

- name: "create or get postgres password"
  set_fact: database_password="{{ lookup('password', '~/credentials/' + deployer + '_postgres length=15') }}"

- when: "action == 'setup' and setup_postgres == True"
  include: postgres.yml

- include: elixir-project.yml

- when: "build_frontend == True"
  include: frontend.yml

- include: elixir-release.yml

- when: action == "setup"
  include: nginx.yml

- when: action == "setup"
  include: monit.yml

- name: start app daemon using monit
  monit: name="{{ project_name }}" state=started
