---
- name: install monit
  apt: name=monit update_cache=yes


- name: allow localhost access in monit config
  lineinfile: dest=/etc/monit/monitrc line="{{ item }}"
  with_items:
    - "set httpd port 2812 and"
    - "use address localhost"
    - "allow localhost"


- name: start monit & mark to be started on system reboots
  service: name=monit state=started enabled=yes
  notify:
    - restart monit


- name: add monit config for elixir app
  template:
    src: app.monit.j2
    dest: "/etc/monit/conf.d/{{ app_name }}.monit"
  notify:
    - reload monit


- name: add monit config for nginx
  template:
    src: nginx.monit.j2
    dest: "/etc/monit/conf.d/nginx.monit"
  notify:
    - reload monit
