---
- name: "compute database name"
  set_fact: "database_name={{ app_name }}_{{mix_env}}"


- name: "create or get postgres password"
  set_fact: database_password="{{ lookup('password', credentials_dir + deploy_as + '-postgres length=15') }}"
  become: "{{primary_user_sudo}}"


- name: "set database user"
  set_fact: database_user="{{ deploy_as }}"