---
- name: "compute database name"
  set_fact: "database_name={{ app_name }}_{{mix_env}}"


- name: "create or get postgres password"
  set_fact: database_password="{{ lookup('password', '~/credentials/' + deployer + '_postgres length=15') }}"


- name: "set database user"
  set_fact: database_user="{{ deployer }}"
