---
- name: "clone project"
  git:
    repo: "{{ repo_url }}"
    version: "{{ git_ref }}"
    dest: "{{ project_path }}"
    accept_hostkey: True
  remote_user: "{{ deployer }}"


- name: "install tool versions"
  command: bash -lc 'asdf install' chdir="{{ project_path }}"
  async: 1800
  remote_user: "{{ deployer }}"


- name: check if custom template for prod.secret.exs exists
  local_action: stat path="templates/prod.secret.exs.j2"
  register: custom_prod_secret_template


- when: custom_prod_secret_template.exists == False
  name: add prod.secret.exs from default template
  template:
    src: default-prod.secret.exs.j2
    dest: "{{ project_path}}/config/prod.secret.exs"
  remote_user: "{{ deployer }}"


- when: custom_prod_secret_template.exists == True
  name: add prod.secret.exs from custom template provided
  template:
    src: templates/prod.secret.exs.j2
    dest: "{{ project_path}}/config/prod.secret.exs"
  remote_user: "{{ deployer }}"


- name: install hex
  command: bash -lc "mix local.hex --force" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: install rebar
  command: bash -lc "mix local.rebar --force" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: "fetch mix dependencies"
  command: bash -lc 'mix deps.get' chdir="{{ project_path }}"
  async: 900
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
