---
- name: "clone project"
  git:
    repo: "{{ repo_url }}"
    version: "{{ git_ref }}"
    dest: "{{ project_path }}"
    accept_hostkey: True
    force: True
  remote_user: "{{ deployer }}"


- name: "install tool versions"
  command: bash -lc 'asdf install' chdir="{{ project_path }}"
  async: 1800
  remote_user: "{{ deployer }}"


- when: (grep_endpoint_module.stdout != "" and grep_repo_module.stdout != "")
  include: app-prod-secret.yml


- name: check if conform config exists
  local_action: stat path="templates/{{ app_name }}.conf.j2"
  register: conform_config_template


- when: conform_config_template.stat.exists == True
  name: add conform config from custom template provided
  template:
    src: "templates/{{ app_name }}.conf.j2"
    dest: "{{ project_path }}/config/{{ app_name }}.conf"
  remote_user: "{{ deployer }}"


- name: install hex
  command: bash -lc "mix local.hex --force" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: install rebar
  command: bash -lc "mix local.rebar --force" chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"


- name: "fetch mix dependencies"
  command: bash -lc 'mix deps.get' chdir="{{ project_path }}"
  async: 900
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
