---
- include: common.yml

- name: "check for swap file path"
  stat: path="/swap"
  register: swap_info

- when: "create_swap_file == True and swap_info.stat.exists == False"
  include: create-swap-file.yml

- include: pip.yml
- include: deployer-user.yml
- include: asdf.yml

- when: "setup_postgres == True"
  include: postgres.yml
  tags:
    - postgres


- include: nginx.yml
- include: monit.yml
