---
- name: "create release using exrm"
  command: bash -lc 'SERVER=1 mix release' chdir="{{ project_path }}"
  remote_user: "{{ deployer }}"
  environment:
    MIX_ENV: "{{ mix_env }}"
    PORT: "{{ app_port }}"
